//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeon_Teller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeon_Teller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Attach {
            get {
                object obj = ResourceManager.GetObject("Attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bar {
            get {
                object obj = ResourceManager.GetObject("bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Alterac Valley
        ///2,Warsong Gulch
        ///3,Arathi Basin
        ///4,Nagrand Arena
        ///5,Blade&apos;s Edge Arena
        ///6,All Arenas
        ///7,Eye of the Storm
        ///8,Ruins of Lordaeron
        ///9,Strand of the Ancients
        ///10,Dalaran Sewers
        ///11,The Ring of Valor
        ///30,Isle of Conquest
        ///32,Random Battleground
        ///100,Rated Battleground
        ///101,Rated Battleground
        ///102,Rated Battleground
        ///108,Twin Peaks
        ///120,The Battle for Gilneas
        ///656,Rated Eye of the Storm
        ///699,Temple of Kotmogu
        ///706,CTF3
        ///708,Silvershard Mines
        ///719,Tol&apos;Viron Arena
        ///754,Deepwind Gorge
        ///757,The Tiger [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BattlefieldIDs {
            get {
                return ResourceManager.GetString("BattlefieldIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dungeon_finder_icon {
            get {
                object obj = ResourceManager.GetObject("dungeon_finder_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Wailing Caverns
        ///2,Scholomance
        ///4,Ragefire Chasm
        ///6,Deadmines
        ///8,Shadowfang Keep
        ///10,Blackfathom Deeps
        ///12,Stormwind Stockade
        ///14,Gnomeregan
        ///16,Razorfen Kraul
        ///20,Razorfen Downs
        ///22,Uldaman
        ///24,Zul&apos;Farrak
        ///26,Maraudon - Foulspore Cavern
        ///28,Sunken Temple
        ///30,Blackrock Depths - Detention Block
        ///32,Lower Blackrock Spire
        ///34,Dire Maul - Warpwood Quarter
        ///36,Dire Maul - Capital Gardens
        ///38,Dire Maul - Gordok Commons
        ///40,Stratholme - Main Gate
        ///46,Onyxia&apos;s Lair
        ///48,Molten Core
        ///50,Blackwing Lair
        ///58,Elwynn Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dungeonids {
            get {
                return ResourceManager.GetString("dungeonids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_missing {
            get {
                object obj = ResourceManager.GetObject("file_missing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lfg_eye {
            get {
                object obj = ResourceManager.GetObject("lfg_eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pvp_finder_icon {
            get {
                object obj = ResourceManager.GetObject("pvp_finder_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raid_finder_icon {
            get {
                object obj = ResourceManager.GetObject("raid_finder_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Ready {
            get {
                return ResourceManager.GetStream("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap role_dps_32x32 {
            get {
                object obj = ResourceManager.GetObject("role_dps_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap role_heal_32x32 {
            get {
                object obj = ResourceManager.GetObject("role_heal_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap role_tank_32x32 {
            get {
                object obj = ResourceManager.GetObject("role_tank_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumps_up {
            get {
                object obj = ResourceManager.GetObject("thumps_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
